steps:

- id: "Copy robots.txt file"
  name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', "gs://analytics_chatbox-box-config/robots.txt", "./public/"]

- id: "Copy sitemap.xml file"
  name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', "gs://analytics_chatbox-box-config/sitemap.xml", "./public/"]

- id: "Copy script Firebase"
  name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', "gs://firebase_chatbox-config/conf-firebase.js", "./src/"]

- id: "install dependency"
  name: 'gcr.io/cloud-builders/npm'
  args: ['install']

- id: "Build static files"
  name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'build']

- id: "Download Express server"
  name: 'gcr.io/cloud-builders/git'
  args: ['clone', 'https://source.developers.google.com/p/chatbox-236716/r/github_yoanndelattre_express-server-gcp', './master/github_yoanndelattre_express-server-gcp']

- id: "Create app_files folder"
  name: 'ubuntu'
  args: ['bash', './master/github_yoanndelattre_express-server-gcp/deploy/CreateFolderApp.sh']

- id: "Move Website Chatbox Project folder"
  name: 'gcr.io/cloud-builders/gsutil'
  args: ['rsync', '-d', '-r', './build/.', './master/github_yoanndelattre_express-server-gcp/app_files/']

- id: "Move WebsiteChatboxConfigAppEngine.yaml in github_yoanndelattre_express-server-gcp folder"
  name: 'gcr.io/cloud-builders/gsutil'
  args: ['mv', './deploy/WebsiteChatboxConfigAppEngine.yaml', './master/github_yoanndelattre_express-server-gcp/']

- id: "DEPLOY APP ENGINE"
  name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy', './master/github_yoanndelattre_express-server-gcp/WebsiteChatboxConfigAppEngine.yaml', './deploy/dispatch.yaml', '--version=1']