steps:

- id: "Import Firebase config"
  name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', 'gs://chatbox_firebase_conf/conf-firebase.js', './src/']

- id: "Pull app image"
  name: 'gcr.io/cloud-builders/docker'
  args: ['pull', 'gcr.io/chatbox-project-256619/chatbox:latest']

- id: "Build app image"
  name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/chatbox-project-256619/chatbox:latest', '.']

- id: "Push app image"
  name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/chatbox-project-256619/chatbox:latest']

- id: "Deploy new app image"
  name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'run', 'deploy', 'chatbox', '--image=gcr.io/chatbox-project-256619/chatbox:latest', '--region=us-central1', '--allow-unauthenticated', '--concurrency=30', '--platform=managed', '--timeout=1m', '--max-instances=6', '--memory=256Mi']